### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by ghost** [jayamanikharyono/tableau-workbook-action#7]
Hi @jayamanikharyono I am getting list index out of range error while running the pipeline

<img width="962" alt="Screen Shot 2022-08-15 at 10 02 58 PM" src="https://user-images.githubusercontent.com/108447479/184681419-320599c4-b305-4444-ab1d-0cffb5db516c.png">

**Comment by ghost** [comment]
@jayamanikharyono any update on this?

**Comment by jayamanikharyono** [comment]
Been fixed in this pr #8
